language: scala
jdk:
  - oraclejdk8
scala:
  - 2.12.4
script:
  - sbt test
notifications:
  email:
    recipients:
      - vaun-pierre@hotmail.com
    on_success: never # default: change
    on_failure: always # default: always