language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
script:
  - sbt test
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash framework/bin/sourceclear; fi'
notifications:
  email:
    recipients:
      - vaun-pierre@hotmail.com
    on_success: never # default: change
    on_failure: always # default: always